environment:
  matrix:
    nodejs_version:
      - '12'

plaftorm:
  - x64

matrix:
  fast_finish: true

shallow_clone: true

install:
  - ps: |
    try {
      Install-Product node $env:nodejs_version $env:platform
    } catch {
      echo "Unable to install node $env:nodejs_version, trying update..."
      Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
    }
  - yarn --frozen-lockfile --non-interactive --no-progress

test_script:
  - node --version
  - yarn --version
  - yarn ci:pipelines

build: off
deploy: off

cache:
  - node_modules -> yarn.lock
