sudo: required
dist: trusty

language: node_js
node_js: '12'

dist: trusty
sudo: false

cache:
  yarn: true
  directories:
    - node_modules

install: yarn --frozen-lockfile --non-interactive --no-progress

script: yarn ci:pipelines
